### ISSUE TITLE
0.1.3 release request

### ISSUE THREAD

**Issue by bruno-delfino1995** [CertainLach/structdump-rs#2]
Could you please release a new minor version to make available the changes introduced by #1?

I'm planning to update `kct` to the latest version of `jrsonnet`, and I would also like to stay at the latest `syn` version.

**Comment by CertainLach** [comment]
Latest version of jrsonnet doesn't uses it, as feature codegenerated-stdlib was removed

**Comment by bruno-delfino1995** [comment]
Oh, that's good to know. Thank you for letting me know, and sorry for any inconvenience.

I'll be upgrading soon :smile:
